#' @keywords internal
"_PACKAGE"


## usethis namespace: start

#' @import shiny
#' @importFrom anytime anydate
#' @importFrom anytime anytime
#' @importFrom bslib accordion
#' @importFrom bslib accordion_panel
#' @importFrom bslib card
#' @importFrom bslib card_header
#' @importFrom bslib input_switch
#' @importFrom bslib layout_columns
#' @importFrom bslib page_fluid
#' @importFrom dplyr across
#' @importFrom dplyr anti_join
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr cur_column
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr join_by
#' @importFrom dplyr lag
#' @importFrom dplyr lead
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr reframe
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom DT datatable
#' @importFrom DT DTOutput
#' @importFrom DT JS
#' @importFrom DT renderDT
#' @importFrom forecast na.interp
#' @importFrom fs path_home
#' @importFrom fs path_package
#' @importFrom fs path_rel
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom htmltools htmlDependency
#' @importFrom lubridate ceiling_date
#' @importFrom lubridate floor_date
#' @importFrom lubridate force_tz
#' @importFrom lubridate hours
#' @importFrom lubridate minutes
#' @importFrom lubridate parse_date_time
#' @importFrom lubridate period
#' @importFrom lubridate round_date
#' @importFrom lubridate tz
#' @importFrom magrittr %>%
#' @importFrom missForest missForest
#' @importFrom nasapower get_power
#' @importFrom plotly add_trace
#' @importFrom plotly plotly_build
#' @importFrom plotly event_data
#' @importFrom plotly event_register
#' @importFrom plotly layout
#' @importFrom plotly plot_ly
#' @importFrom plotly plotlyOutput
#' @importFrom plotly renderPlotly
#' @importFrom plotly style
#' @importFrom plotly toWebGL
#' @importFrom pracma hampel
#' @importFrom readr guess_encoding
#' @importFrom rlang .data
#' @importFrom rlang `:=` !!
#' @importFrom rlang empty_env
#' @importFrom rlang env_bind
#' @importFrom rlang new_environment
#' @importFrom rlang sym
#' @importFrom shinyalert shinyalert
#' @importFrom shinyFiles parseSavePath
#' @importFrom shinyFiles shinyFileSave
#' @importFrom shinyFiles shinySaveButton
#' @importFrom shinyjs reset
#' @importFrom shinyjs useShinyjs
#' @importFrom stats as.formula
#' @importFrom stats median
#' @importFrom stats na.omit
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom stats ts
#' @importFrom stringr str_split_i
#' @importFrom tidyr complete
#' @importFrom tidyr drop_na
#' @importFrom tidyr fill
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyselect all_of
#' @importFrom timeplyr time_diff
#' @importFrom tools file_ext
#' @importFrom utf8 as_utf8
#' @importFrom utils read.csv
#' @importFrom utils write.csv
#' @importFrom vctrs vec_compare
#' @importFrom withr local_tempdir
#' @importFrom zoo na.approx
#' @importFrom zoo na.locf
#' @importFrom zoo rollmedian
## usethis namespace: end
NULL
