#' @keywords internal
"_PACKAGE"


## usethis namespace: start

#' @import shiny
#' @importFrom anytime addFormats
#' @importFrom anytime anydate
#' @importFrom anytime anytime
#' @importFrom anytime removeFormats
#' @importFrom bslib accordion
#' @importFrom bslib accordion_panel
#' @importFrom bslib card
#' @importFrom bslib card_header
#' @importFrom bslib input_switch
#' @importFrom bslib layout_columns
#' @importFrom bslib page_fluid
#' @importFrom daff diff_data
#' @importFrom daff patch_data
#' @importFrom digest digest
#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr lag
#' @importFrom dplyr lead
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom DT datatable
#' @importFrom DT DTOutput
#' @importFrom DT JS
#' @importFrom DT renderDT
#' @importFrom fs path_home
#' @importFrom fs path_package
#' @importFrom fs path_rel
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 scale_color_manual
#' @importFrom htmltools htmlDependency
#' @importFrom lubridate force_tz
#' @importFrom lubridate round_date
#' @importFrom lubridate tz
#' @importFrom magrittr %>%
#' @importFrom plotly event_data
#' @importFrom plotly event_register
#' @importFrom plotly ggplotly
#' @importFrom plotly layout
#' @importFrom plotly plotlyOutput
#' @importFrom plotly renderPlotly
#' @importFrom readr guess_encoding
#' @importFrom rlang .data
#' @importFrom rlang `:=` !!
#' @importFrom rlang empty_env
#' @importFrom rlang env_bind
#' @importFrom rlang new_environment
#' @importFrom rlang sym
#' @importFrom rprojroot find_package_root_file
#' @importFrom rprojroot find_rstudio_root_file
#' @importFrom sf st_agr
#' @importFrom sf st_as_sf
#' @importFrom sf st_intersection
#' @importFrom sf st_transform
#' @importFrom shinyalert shinyalert
#' @importFrom shinyFiles parseDirPath
#' @importFrom shinyFiles parseSavePath
#' @importFrom shinyFiles shinyDirButton
#' @importFrom shinyFiles shinyDirChoose
#' @importFrom shinyFiles shinyFileSave
#' @importFrom shinyFiles shinySaveButton
#' @importFrom shinyWidgets updateSwitchInput
#' @importFrom stats quantile
#' @importFrom stats setNames
#' @importFrom stringi stri_enc_detect
#' @importFrom stringr str_split_i
#' @importFrom terra crs
#' @importFrom terra ext
#' @importFrom thematic thematic_shiny
#' @importFrom tidyr drop_na
#' @importFrom tidyselect all_of
#' @importFrom tools file_ext
#' @importFrom utf8 as_utf8
#' @importFrom utils read.csv
#' @importFrom withr local_tempdir
## usethis namespace: end
NULL
